import { AnalysisPipelineResult } from '../types/engine';

export const MOCK_ANALYSIS_RESULT: AnalysisPipelineResult = {
  healthScore: 62,
  summary: {
    totalFilesScanned: 12,
    relevantArtifactsCount: 8,
    ignoredFilesCount: 4,
    filesByArtifactType: {
      CODE: 4,
      DOCS: 1,
      SPEC: 1,
      CONFIG: 1,
      TEST: 1,
    },
    filesByFormat: {
      typescript: 5,
      markdown: 1,
      yaml: 1,
      env: 1,
      javascript: 0,
      json: 0,
      unknown: 0,
    },
    metrics: {
      totalRoutes: 2,
      totalOpenApiEndpoints: 2,
      totalEnvVariablesDeclared: 1,
      totalEnvReferencesInCode: 1,
      totalTestFiles: 1,
      totalExportedSymbols: 6,
    },
  },
  scanResult: {
    targetPath: 'demo-repo',
    scanDurationMs: 85,
    totalFilesScanned: 12,
    relevantArtifactsCount: 8,
    artifacts: [],
  },
  artifacts: [],
  claims: [
    {
      id: 'claim:README.md:grace:24h',
      artifactId: 'artifact:README.md',
      filePath: 'README.md',
      startLine: 18,
      endLine: 21,
      sourceType: 'DOCS',
      rawSnippet: '### Subscriptions & Cancellation\nUsers can cancel their active subscription for a full refund within 24 hours of purchase.',
      subject: 'domain:user_cancellation_period',
      assertion: 'README claims cancellation grace period for full refund is strictly 24 hours.',
    },
    {
      id: 'claim:openapi.yaml:grace:24h',
      artifactId: 'artifact:openapi.yaml',
      filePath: 'openapi.yaml',
      startLine: 28,
      endLine: 34,
      sourceType: 'SPEC',
      rawSnippet: '    /subscription/cancel:\n      post:\n        summary: Cancel user subscription\n        description: Cancel active subscription within 24 hours grace period for refund.',
      subject: 'domain:user_cancellation_period',
      assertion: 'OpenAPI specification description asserts 24 hours cancellation grace period.',
    },
    {
      id: 'claim:src/controllers/subscription.ts:grace:48h',
      artifactId: 'artifact:src/controllers/subscription.ts',
      filePath: 'src/controllers/subscription.ts',
      startLine: 14,
      endLine: 22,
      sourceType: 'CODE',
      rawSnippet: '  const maxGraceHours = 48;\n  if (elapsedHours > maxGraceHours) {\n    return res.status(400).json({\n      error: "Cancellation window expired. Requests must be within 48 hours.",\n    });\n  }',
      subject: 'domain:user_cancellation_period',
      assertion: 'SubscriptionController enforces maxGraceHours = 48 hours before rejecting cancellation.',
      symbolName: 'cancelSubscription',
    },
  ],
  graph: {
    nodes: [
      { id: 'artifact:README.md', type: 'ARTIFACT', label: 'README.md', data: {} },
      { id: 'artifact:openapi.yaml', type: 'ARTIFACT', label: 'openapi.yaml', data: {} },
      { id: 'artifact:src/controllers/subscription.ts', type: 'ARTIFACT', label: 'src/controllers/subscription.ts', data: {} },
      { id: 'subject:domain:user_cancellation_period', type: 'SUBJECT', label: 'domain:user_cancellation_period', data: {} },
      { id: 'subject:route:POST /api/v1/auth/token', type: 'SUBJECT', label: 'route:POST /api/v1/auth/token', data: {} },
      { id: 'subject:env:ENABLE_RATE_LIMITING', type: 'SUBJECT', label: 'env:ENABLE_RATE_LIMITING', data: {} },
    ],
    edges: [
      { id: 'e1', source: 'artifact:README.md', target: 'subject:domain:user_cancellation_period', relation: 'ADDRESSES' },
      { id: 'e2', source: 'artifact:openapi.yaml', target: 'subject:domain:user_cancellation_period', relation: 'ADDRESSES' },
      { id: 'e3', source: 'artifact:src/controllers/subscription.ts', target: 'subject:domain:user_cancellation_period', relation: 'ADDRESSES' },
    ],
  },
  findings: [
    {
      id: 'contradiction:hero:grace-period',
      subject: 'domain:user_cancellation_period',
      category: 'BEHAVIORAL',
      title: '3-Way Cancellation Grace Period Discrepancy (Hero Contradiction)',
      summary: 'Documentation and OpenAPI specification state a 24-hour cancellation window, whereas subscription controller logic enforces 48 hours.',
      conflictingClaims: [
        {
          id: 'claim:readme:grace:24h',
          artifactId: 'artifact:README.md',
          filePath: 'README.md',
          startLine: 18,
          endLine: 21,
          sourceType: 'DOCS',
          rawSnippet: '### Subscriptions & Cancellation\nUsers can cancel their active subscription for a full refund within 24 hours of purchase.\nRequests beyond 24 hours will be processed without refund.',
          subject: 'domain:user_cancellation_period',
          assertion: 'README claims cancellation grace period for full refund is strictly 24 hours.',
        },
        {
          id: 'claim:openapi:grace:24h',
          artifactId: 'artifact:openapi.yaml',
          filePath: 'openapi.yaml',
          startLine: 28,
          endLine: 34,
          sourceType: 'SPEC',
          rawSnippet: '    /subscription/cancel:\n      post:\n        summary: Cancel user subscription\n        description: Cancel active subscription within 24 hours grace period for refund.',
          subject: 'domain:user_cancellation_period',
          assertion: 'OpenAPI specification description asserts 24 hours cancellation grace period.',
        },
        {
          id: 'claim:controller:grace:48h',
          artifactId: 'artifact:src/controllers/subscription.ts',
          filePath: 'src/controllers/subscription.ts',
          startLine: 14,
          endLine: 22,
          sourceType: 'CODE',
          rawSnippet: '  // Grace period threshold check\n  const maxGraceHours = 48;\n  if (elapsedHours > maxGraceHours) {\n    return res.status(400).json({\n      error: "Cancellation window expired. Requests must be within 48 hours.",\n    });\n  }',
          subject: 'domain:user_cancellation_period',
          assertion: 'SubscriptionController enforces maxGraceHours = 48 hours before rejecting cancellation.',
          symbolName: 'cancelSubscription',
        },
      ],
      incompatibilityReason: 'The business logic predicate in code (`elapsedHours > 48`) contradicts explicit claims in README and OpenAPI spec (`24 hours`). Users allowed 48 hours in execution will exceed documented terms.',
      confidenceScore: 0.99,
      severity: 'CRITICAL',
      probabilisticSourceOfTruth: {
        filePath: 'src/controllers/subscription.ts',
        probability: 0.82,
        reasoning: 'Controller source code in subscription.ts directly governs production runtime execution path and status codes.',
      },
      status: 'OPEN',
    },
    {
      id: 'contradiction:schema:taxId:/billing/charge',
      subject: 'schema:POST /billing/charge:taxId',
      category: 'API_CONTRACT',
      title: 'Required Field Schema Conflict: OpenAPI vs Zod Validation',
      summary: 'OpenAPI spec defines parameter "taxId" as optional for /billing/charge, but controller validation schema requires "taxId".',
      conflictingClaims: [
        {
          id: 'claim:openapi:taxId:optional',
          artifactId: 'artifact:openapi.yaml',
          filePath: 'openapi.yaml',
          startLine: 42,
          endLine: 48,
          sourceType: 'SPEC',
          rawSnippet: '    /billing/charge:\n      post:\n        requestBody:\n          required:\n            - amount\n            - currency',
          subject: 'schema:POST /billing/charge:taxId',
          assertion: 'OpenAPI spec marks "taxId" as optional or omitted from required list.',
        },
        {
          id: 'claim:code:taxId:required',
          artifactId: 'artifact:src/controllers/billing.ts',
          filePath: 'src/controllers/billing.ts',
          startLine: 12,
          endLine: 18,
          sourceType: 'CODE',
          rawSnippet: 'export const billingSchema = z.object({\n  amount: z.number().positive(),\n  currency: z.string().length(3),\n  taxId: z.string().min(1, "Tax ID is required"),\n});',
          subject: 'schema:POST /billing/charge:taxId',
          assertion: 'Zod controller schema strictly requires non-empty string "taxId".',
          symbolName: 'billingSchema',
        },
      ],
      incompatibilityReason: 'API clients sending requests compliant with the OpenAPI specification (omitting taxId) will experience unhandled HTTP 400 Bad Request validation failures in production.',
      confidenceScore: 0.96,
      severity: 'CRITICAL',
      probabilisticSourceOfTruth: {
        filePath: 'src/controllers/billing.ts',
        probability: 0.88,
        reasoning: 'Runtime Zod validation in src/controllers/billing.ts immediately rejects incoming payloads if "taxId" is missing.',
      },
      status: 'OPEN',
    },
    {
      id: 'contradiction:route:/api/v1/auth/login:/api/v1/auth/token',
      subject: 'route:POST /api/v1/auth/token',
      category: 'STRUCTURAL',
      title: 'API Route Endpoint Discrepancy: Documentation vs Code',
      summary: 'Documentation claims endpoint "POST /api/v1/auth/login" exists, but source code implements "POST /api/v1/auth/token".',
      conflictingClaims: [
        {
          id: 'claim:doc:route:/api/v1/auth/login',
          artifactId: 'artifact:README.md',
          filePath: 'README.md',
          startLine: 12,
          endLine: 14,
          sourceType: 'DOCS',
          rawSnippet: '### Authentication\nPOST /api/v1/auth/login - Request authentication token',
          subject: 'route:POST /api/v1/auth/login',
          assertion: 'Documentation claims endpoint POST /api/v1/auth/login exists.',
        },
        {
          id: 'claim:code:route:/api/v1/auth/token',
          artifactId: 'artifact:src/routes/auth.ts',
          filePath: 'src/routes/auth.ts',
          startLine: 8,
          endLine: 10,
          sourceType: 'CODE',
          rawSnippet: 'router.post("/api/v1/auth/token", handleTokenRequest);',
          subject: 'route:POST /api/v1/auth/token',
          assertion: 'Source code registers route POST /api/v1/auth/token.',
          symbolName: 'handleTokenRequest',
        },
      ],
      incompatibilityReason: 'The documented route path "/api/v1/auth/login" differs from the actual implemented route path "/api/v1/auth/token". Clients following documentation will receive HTTP 404.',
      confidenceScore: 0.98,
      severity: 'HIGH',
      probabilisticSourceOfTruth: {
        filePath: 'src/routes/auth.ts',
        probability: 0.9,
        reasoning: 'Code implementation in src/routes/auth.ts represents actual runtime execution routing.',
      },
      status: 'OPEN',
    },
    {
      id: 'contradiction:env:ENABLE_RATE_LIMITING:RATE_LIMIT_ENABLED',
      subject: 'env:ENABLE_RATE_LIMITING',
      category: 'CONFIGURATION',
      title: 'Environment Variable Name Mismatch',
      summary: '.env.example defines key "ENABLE_RATE_LIMITING", but runtime configuration in src/config/app.ts checks process.env.RATE_LIMIT_ENABLED.',
      conflictingClaims: [
        {
          id: 'claim:env:def:ENABLE_RATE_LIMITING',
          artifactId: 'artifact:.env.example',
          filePath: '.env.example',
          startLine: 4,
          endLine: 4,
          sourceType: 'CONFIG',
          rawSnippet: 'ENABLE_RATE_LIMITING=true',
          subject: 'env:ENABLE_RATE_LIMITING',
          assertion: '.env.example defines configuration variable "ENABLE_RATE_LIMITING".',
          symbolName: 'ENABLE_RATE_LIMITING',
        },
        {
          id: 'claim:env:code:RATE_LIMIT_ENABLED',
          artifactId: 'artifact:src/config/app.ts',
          filePath: 'src/config/app.ts',
          startLine: 6,
          endLine: 6,
          sourceType: 'CODE',
          rawSnippet: 'export const rateLimitingEnabled = process.env.RATE_LIMIT_ENABLED === "true";',
          subject: 'env:RATE_LIMIT_ENABLED',
          assertion: 'Application code reads environment variable "process.env.RATE_LIMIT_ENABLED".',
          symbolName: 'RATE_LIMIT_ENABLED',
        },
      ],
      incompatibilityReason: 'Environment variable "ENABLE_RATE_LIMITING" provided in deployment template will not be read by code looking for "RATE_LIMIT_ENABLED". Feature flag will silently fallback to default.',
      confidenceScore: 0.95,
      severity: 'HIGH',
      probabilisticSourceOfTruth: {
        filePath: 'src/config/app.ts',
        probability: 0.85,
        reasoning: 'Code in src/config/app.ts directly controls execution logic and variable references at runtime.',
      },
      status: 'OPEN',
    },
    {
      id: 'contradiction:test:auth:status_code',
      subject: 'domain:auth_endpoint',
      category: 'TESTING',
      title: 'HTTP Status Code Contradiction: Documentation vs Test Assertion',
      summary: 'Documentation states expired auth tokens return HTTP 401 Unauthorized, but integration test asserts HTTP 403 Forbidden.',
      conflictingClaims: [
        {
          id: 'claim:doc:auth:401',
          artifactId: 'artifact:README.md',
          filePath: 'README.md',
          startLine: 32,
          endLine: 35,
          sourceType: 'DOCS',
          rawSnippet: '### Authentication Errors\nRequests with expired tokens receive HTTP 401 Unauthorized with error code TOKEN_EXPIRED.',
          subject: 'domain:auth_endpoint',
          assertion: 'Documentation asserts expired tokens return status 401 Unauthorized.',
        },
        {
          id: 'claim:test:auth:403',
          artifactId: 'artifact:tests/auth.test.ts',
          filePath: 'tests/auth.test.ts',
          startLine: 12,
          endLine: 22,
          sourceType: 'TEST',
          rawSnippet: '  it("should reject expired token with 403", async () => {\n    const res = await request(app).post("/api/v1/auth/token").set("Authorization", "Bearer expired");\n    expect(res.status).toBe(403);\n  });',
          subject: 'domain:auth_endpoint',
          assertion: 'Jest test asserts response status code is HTTP 403 Forbidden.',
        },
      ],
      incompatibilityReason: 'Documented HTTP response status (401 Unauthorized) conflicts with automated test suite expectation (403 Forbidden), causing API integrations and unit tests to disagree.',
      confidenceScore: 0.94,
      severity: 'MEDIUM',
      probabilisticSourceOfTruth: {
        filePath: 'tests/auth.test.ts',
        probability: 0.78,
        reasoning: 'Automated test suite suite in tests/auth.test.ts reflects enforced API contract verification.',
      },
      status: 'OPEN',
    },
  ],
};
